name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: http://localhost:3000
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install and start mock API
        working-directory: mocks/server
        run: |
          npm install
          nohup npm start &
          # Wait up to ~30s for health to be ready
          for i in $(seq 1 30); do
            if curl -fsS http://localhost:3000/health > /dev/null; then
              echo "API is healthy"
              break
            fi
            sleep 1
          done
          # Fail if not healthy
          curl -fsS http://localhost:3000/health

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Run API tests
        run: pytest -q

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Performance smoke
        run: k6 run tests/performance/create_payment.js
